### ISSUE TITLE
Change internal data structure of (output) Shifters

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-FirmwareSource#138]
For consistency with InputShifters; use a byte array in place of a fixed word.
No practical advantages currently.

**Comment by neilenns** [comment]
Agreed, it always bugged me that it wasn't done using arrays.

**Comment by GioCC** [comment]
It has a rationale, though, because exceeding 32 bits is rather unlikely; that would mean a longer hardware chain and that's not something you would want to have. But hey, it bugged me a little too.
