### ISSUE TITLE
Stepper Motor is Holding the Current Position

### ISSUE THREAD

**Issue by coreflighttech** [MobiFlight/MobiFlight-FirmwareSource#193]
I'm using ULN2003 and 28BYJ-48 5V step motor driven by MF.
After working for a while, it gets too hot and draws the overcurrent until it burns.
Adding a function that does not hold the step motor can be a good idea because no gauge needs that holding torque.

**Comment by DocMoebiuz** [comment]
@coreflighttech - how are you powering the stepper? Is it an external supply with 5V?

**Comment by coreflighttech** [comment]
@DocMoebiuz it's powered by Arduino 5V.

**Comment by elral** [comment]
Optionally disabling the outputs is implemented with PR #224
