### ISSUE TITLE
Increase the supported Mux for Mega to 3 devices

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-FirmwareSource#194]
At the moment we can only add up to 2 16-bit Mux modules.
Tests have shown, that you can have 3 connected in a stable way.

So we can up increase the limit to 3 on the mega. Uno and Pro Micro can stay the same.

**Comment by GioCC** [comment]
Memory-wise, even increasing the max number to 6-4-6 (from 2-1-2) makes negligible difference.
Since they should be increased, is there any specific reason not to increase them by this much?

**Comment by DocMoebiuz** [comment]
There is no specific reason. I think 4 per module is at the moment good enough, since they can only be used as buttons.
4-2-2 (mega, promicro, uno) or 4-3-3 is totally sufficient.

**Comment by DocMoebiuz** [comment]
This requires a change on the connector too.

**Comment by DocMoebiuz** [comment]
Goal would be to have this for Lelystad. I assigned it to you @GioCC, is that OK?

**Comment by neilenns** [comment]
@DocMoebiuz You can assign this to me, I can do it today. It's pretty quick.

**Comment by DocMoebiuz** [comment]
cool

**Comment by neilenns** [comment]
> cool

Too late, @GioCC already has a PR out 😂
