### ISSUE TITLE
Cleanup of multiplexer device code

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-FirmwareSource#204]
Remove code that handles "lazy" mode from multiplexer to simplify and gain space.
That mode is not in use and neither was it going to be used anytime soon (or ever).
(PR is ready and will be pushed as soon as previous pending modifications are closed).

**Comment by DocMoebiuz** [comment]
> Remove code that handles "lazy" mode from multiplexer to simplify and gain space. That mode is not in use and neither was it going to be used anytime soon (or ever). 

This statement indicates, that this change is not necessary. Please close this issue if there are no functional or non-functional reasons, @GioCC. Thanks!

**Comment by GioCC** [comment]
Having totally useless code lying around and wasting space is no concern?

**Comment by DocMoebiuz** [comment]
It might have been already late when i read the description. Sorry. I must have read it totally wrong.

Code that is not used and will not be used any time soon can be removed of course to save memory space and reduce code size.

@GioCC go for it.

**Comment by GioCC** [comment]
No problem, that just seemed a little odd. I'll file the PR.
Thanks
