### ISSUE TITLE
Change constant for averaging buffer size of analog inputs

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-FirmwareSource#211]
Currently, two independently defined constants are used:
```
#define ADC_MAX_AVERAGE      8 // must be 2^n
#define ADC_MAX_AVERAGE_LOG2 3 // please calculate LOG2(ADC_MAX_AVERAGE)
```
These should be bound to the same value, in order to avoid accidental misalignments:
```
#define ADC_MAX_AVERAGE_LOG2 3
#define ADC_MAX_AVERAGE      (1 << ADC_MAX_AVERAGE_LOG2) // must be 2^n
```

**Comment by elral** [comment]
Great! I was always thinking the other way round, how to get the logN. But in this direction there is no preprocessor directive.

**Comment by elral** [comment]
@GioCC is it OK that I have assigned you?

**Comment by GioCC** [comment]
Sure, of course!

**Comment by elral** [comment]
@GioCC looking on your proposal, the comment `// must be 2^n` could be deleted. Maybe an additional comment behind `#define ADC_MAX_AVERAGE_LOG2 3` might be sensefull to explain that this means an average buffer of 8 byte.
