### ISSUE TITLE
Clean up the build scripts

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-FirmwareSource#235]
While working on some build process stuff for one of my private firmware builds I discovered a few things that need cleaning up:

1. Need to explicitly define `python_version` when downloading python. It should be `3.9`.
2. The caching mechanism isn't right, see https://github.com/platformio/platformio-docs/blob/develop/integration/ci/github-actions.rst
3. No need to do `python -m pip install --upgrade pip` before doing the pip install.

Example of these changes in action is at https://github.com/neilenns/Collins-FMS-3000-Firmware/tree/main/.github/workflows

**Comment by elral** [comment]
@neilenns Is this Issue still open?

**Comment by neilenns** [comment]
Looks like it. I checked the build scripts and everyone of those issues is still present.

**Comment by elral** [comment]
@neilenns could you do the pull request? I am not really familiar with that.
