### ISSUE TITLE
Buttons, encoders, and diginmux actions do not prevent power save mode 

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-FirmwareSource#273]
The button, encoder, and digmuxin code are missing calls to `setLastCommandMillis()`, which means interacting with any of those devices isn't sufficient to prevent power save mode from kicking in.

We should probably call `setLastCommandMillis()` for those input devices too.

Reported by @elral in discord.

**Comment by neilenns** [comment]
This might be a good time to rethink this whole method. Instead of having it be based on things with the device, why isn't it just the desktop sending a keep-alive message as long as "run" mode is active? We already have a defined event for that and it isn't used for anything. Just send it to the connected modules every once and a while.

**Comment by tigert** [comment]
I agree. It is not correct to assume all panels will get data sent to them frequently enough.

My example was an APU EGT gauge created with a stepper motor and led output pin for gauge lighting.

As APU is used mostly just on the ground, the gauge will sit static during most of the flights, with the backlight on but nothing changing as far it is concerned.

I think MF connector should send keepalive events to all panels, whether they actually receive data or not.

**Comment by elral** [comment]
I would change it in the firmware to enable and disable the power saving mode and let the connector decide when and which panel gets one of these commands.
Maybe we can add Neil's proposal as a interim solution as long as the connector is not modified. But it wouldn't solve Tuomas problem...

**Comment by neilenns** [comment]
> I would change it in the firmware to enable and disable the power saving mode and let the connector decide when and which panel gets one of these commands.

The change I opened basically kind of does this. Modules put themselves to sleep after 15 minutes of not receiving a stay awake message from the desktop.
