### ISSUE TITLE
Pin 1 gets set as output or input when a button/analogIn is defined

### ISSUE THREAD

**Issue by elral** [MobiFlight/MobiFlight-FirmwareSource#284]
With PR #253 the fixed device numbers were removed. All devices from one type are now behind each other in the deviceBuffer to reserve sufficient memory and only the pointer for all devices is saved.

To get the pointer it is called: `outputs = new (allocateMemory(sizeof(MFOutput) * count)) MFOutput;`

So the constructor gets called and executed. As the definition of the constructor is `MFOutput(uint8_t pin = 1);`  and the code is:

```
MFOutput::MFOutput(uint8_t pin)
{
    _pin   = pin;
    _value = false;
    pinMode(_pin, OUTPUT); // set pin to input
    set(_value);
}
```

Pin 1 gets set as Output if calculating the required size in the devicebuffer.

The same applies for the AnlogIn.

**Comment by neilenns** [comment]
Woah, subtle bug!

**Comment by elral** [comment]
I reduced everything to the minimum:

```
#include <Arduino.h>
#include "Output.h"

void setup() {
  Serial.begin(115200);
  while(!Serial) delay(10);
  delay(1000);
  Serial.println("Serial initialized");
  Output::setupArray(4);
  Output::Add(2);
  Output::Add(3);
  Output::Add(18);
  Output::Add(19);
}

void loop() {
  Serial.println("Setting output to 255");
  Output::OnSet(2,255);
  Output::OnSet(3,255);
  delay(1000);
  Serial.println("Setting output to 0");
  Output::OnSet(2,0);
  Output::OnSet(3,0);
  delay(1000);
}
```

with slight adaptions to get it run without the CMDMessenger and the onSet() function.

And it still happens.
The good things are, I have a base to to debug it better or to ask earlephilhower, and it is NOT related to our code.
