### ISSUE TITLE
MobiFlight-Customdevices repo should be archived

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-FirmwareSource#316]
Since we now use CommunityDevices and CommunityTemplate, we should archive MobiFlight-Customdevices git repository, since it is very confusing to new people interested in the firmware development.

I mean it has fooled me several times already even though I know about the move :-)

**Comment by elral** [comment]
That's related to issue #310 and PR #311 .

And yes, latest when the mentioned PR gets merged the MobiFlight-CustomDeiveces repo should be archived.

**Comment by DocMoebiuz** [comment]
The repo was archived some weeks ago. I am closing this now.
